export const breadcrumb = {
	dashboard: "dashboard",
	warehouse: {
		checkWarehouseVN: "Kiểm hàng Việt Nam",
		checkWarehouseTQ: "Kiểm hàng Trung Quốc",
		addPackageCustomer: "Gán kiện ký gửi cho khách",
		floatingPackage: "Danh sách kiện trôi nổi",
		import: "Import excel",
		missingPackage: "Danh sách kiện thất lạc",
		outstock: {main: "Xuất kho", detail: "Chi tiết phiên xuất kho"},
		packageManagement: {
			main: "Quản lý bao hàng",
			detail: "Chi tiết quản lý bao hàng",
		},
		transactionCodeManagement: "Quản lý mã vận đơn",
	},
	statistical: {
		transaction: "Thống kê giao dịch",
		surplus: "Thống kê số dư",
		sales: "Thống kê doanh thu",
		recharge: "Thống kê tiền nạp rút",
		purchaseProfit: "Thống kê lợi nhuận mua hộ",
		paymentProfit: "Thống kê lợi nhuận thanh toán hộ",
		order: "Thống kê đơn hàng",
		money: "Thống kê tiền mua hàng",
		incomeTransport: "Thống kê doanh thu ký gửi",
		incomeSale: "Thống kê doanh thu sale",
		incomeOrder: "Thống kê doanh thu đặt hàng",
		printPurchase: {
			main: "Danh sách đơn hàng mua hộ đã giao khách",
			detail: "Chi tiết thanh toán xuất kho",
		},
	},
	settings: {
		wareHouse: "Quản lý kho Trung Quốc - Việt Nam",
		bank: "Danh sách ngân hàng",
		configration: "Cấu hình hệ thống NHAPHANGDEMO",
		notification: "Cấu hình thông báo",
		tariffBuyPro: "Cấu hình phí dịch vụ mua hàng",
		tariffChinaVietNam: "Cấu hình vận chuyển TQ - VN",
		tariffPriceChange: "Cấu hình phí thanh toán hộ",
		tariffUser: "Cấu hình phí người dùng",
		goodsChecking: "Cấu hình phí kiểm đếm",
	},
	order: {
		complainList: "Khiếu nại",
		orderList: {
			main: "Đơn hàng mua hộ",
			detail: "Chi tiết đơn hàng",
			detailProduct: "Chi tiết sản phẩm",
		},
		payment: {detail: "Thanh toán đơn hàng"},
		requestPayment: {
			main: "Danh sách yêu cầu thanh toán hộ",
			detail: "Chi tiết yêu cầu",
		},
	},
	money: {
		chinaRechargeHistory: "Lịch sử nạp tệ",
		chinaWithdrawalHistory: "Lịch sử rút tệ",
		personalRecharge: "Danh sách khách hàng",
		rechargeHistory: "Lịch sử nạp tiền",
		withdrawalHistory: "Lịch sử rút tiền",
		chinaRecharge: {detail: "Nạp tiền tệ"},
		chinaWithdrawal: {detail: "Rút tiền Trung Quốc"},
		vietnamWithdrawal: {detail: "Rút tiền Việt Nam"},
		vietnamRecharge: {detail: "Nạp tiền Việt Nam"},
		outstockPayment: {
			main: "Thanh toán xuất kho",
			detail: "Chi tiết thanh toán xuất kho",
		},
	},
	employee: {
		bonusManagement: "Quản lý hoa hồng",
		employeeManagement: {
			main: "Danh sách nhân viên",
			detail: "Thông tin tài khoản",
		},
		decentralization: "Quản lý phân quyền",
		groupUser: "Danh sách nhóm user",
	},
	deposit: {
		depositList: {
			main: "Danh sách vận chuyển hộ",
			detail: "Chi tiết vận chuyển",
		},
		depositStatistic: "Thống kê cước vận chuyển hộ",
		nonRequestDepositOutstock: {
			main: "Xuất kho",
			detail: "Chi tiết xuất kho",
		},
		requestedDepositOutstock: "Xuất kho",
	},
	content: {
		addChild: {detail: "Thêm menu"},
		addNew: "Thêm menu",
		edit: {detail: "Chi tiết menu"},
		home: "Cấu hình trang chủ",
	},
	client: {
		clientList: {main: "Danh sách khách hàng", detail: "Thông tin tài khoản"},
		createOrder: {detail: "Tạo đơn hàng"},
		orderList: {detail: "Danh sách đơn hàng"},
		transactionHistory: {detail: "Lịch sử giao dịch"},
		createNewClient: {main: "Thêm khách hàng mới"},
	},
	article: {
		articleCategory: {
			add: "Thêm chuyên mục",
			main: "Danh sách chuyên mục",
			detail: "Chỉnh sửa chuyên mục",
		},
		articleList: {
			detail: "Chỉnh sửa bài viết",
			add: "Thêm bài viết",
			main: "Bài viết",
		},
	},
	notification: "Danh sách thông báo",
};
