export const exportHead = {
  WithdrawType3: [
    [
      "ID",
      "USERNAME",
      "SỐ TIỀN NẠP",
      "TRẠNG THÁI",
      "NGÀY TẠO",
      "NGƯỜI TẠO",
      "NGƯỜI DUYỆT",
      "NGÀY DUYỆT",
    ],
  ],
  WithdrawType2Template: [
    [
      "ID",
      "NGƯỜI THỰC HIỆN GD",
      "HỌ TÊN",
      "STK KHÁCH",
      "NGÂN HÀNG",
      "SỐ TIỀN RÚT",
      "TRẠNG THÁI",
      "NGÀY RÚT",
      "NGƯỜI DUYỆT",
      "NGÀY DUYỆT",
    ],
  ],
  WithdrawReportTemplate: [
    ["ID", "USERNAME", "SỐ TIỀN", "TRẠNG THÁI", "NGÀY TẠO", "NGƯỜI DUYỆT"],
  ],
  UserTemplate: [
    [
      "ID",
      "TÊN ĐĂNG NHẬP",
      "HỌ VÀ TÊN",
      "SỐ ĐIỆN THOẠI",
      "SỐ DƯ",
      "TRẠNG THÁI",
      "VIP",
      "QUYỀN, HẠN",
      "ĐỊA CHỈ",
      "EMAIL",
      "NGÀY TẠO",
    ],
  ],
  UserReportTemplate: [
    [
      "ID",
      "USERNAME",
      "SỐ DƯ",
      "QUYỀN HẠN",
      "TRẠNG THÁI",
      "NV KINH DOANH",
      "NV ĐẶT HÀNG",
      "NGÀY TẠO",
    ],
  ],
  TransportationOrderTemplate: [
    [
      "ID",
      "USERNAME",
      "MÃ VẬN ĐƠN",
      "CÂN NẶNG",
      "KHO TQ",
      "KHO VN",
      "PTVC",
      "TỔNG TIỀN	PHÍ",
      "KIỂM HÀNG",
      "PHÍ BẢO HIỂM",
      "PHÍ ĐÓNG GỖ",
      "PHÍ VẬN CHUYỂN",
      "PHÍ COD TỆ",
      "PHÍ COD VNĐ",
      "NGÀY TẠO",
      "NGÀY XUẤT KHO",
      "TRẠNG THÁI",
    ],
  ],
  TransportationOrderReportTemplate: [
    [
      "MÃ ĐƠN HÀNG",
      "USERNAME",
      "MÃ VẬN ĐƠN",
      "CÂN NẶNG",
      "KHO TQ",
      "KHO VN",
      "PTVC",
      "CƯỚC VẬT TƯ",
      "PP MẶT HÀNG",
      "ĐB",
      "TIỀN CÂN / KG",
      "TỔNG TIỀN",
      "NGÀY TẠO",
      "NGÀY VỀ TQ",
      "NGÀY VỀ VN",
      "NGÀY YCXK",
      "NGÀY XUẤT KHO",
      "TRẠNG THÁI",
    ],
  ],
  StaffIncomeTemplate: [
    [
      "MÃ ĐƠN HÀNG",
      "PHẦN TRĂM,	HOA HỒNG",
      "USERNAME",
      "QUYỀN HẠN",
      "TRẠNG THÁI",
      "NGÀY GIỜ",
    ],
  ],
  SmallPackageTemplate: [
    [
      "ID",
      "USERNAME",
      "BAO HÀNG",
      "MÃ VẬN ĐƠN",
      "MÃ ĐƠN HÀNG",
      "LOẠI HÀNG",
      "CÂN NẶNG (KG)",
      "D x R x C",
      "CÂN TÍNH TIỀN (KG)",
      "TRẠNG THÁI",
      "NGÀY TẠO",
    ],
  ],
  SmallPackageFloatingTemplate: [
    [
      "ID",
      "BAO HÀNG",
      "MÃ VẬN ĐƠN",
      "LOẠI HÀNG",
      "PHÍ SHIP (TỆ)",
      "CÂN (KG)",
      "KHỐI (M)",
      "TRẠNG THÁI",
      "KIỆN",
      "USER NHẬN HÀNG",
      "TRẠNG THÁI",
      "XÁC NHẬN",
      "NGÀY TẠO",
    ],
  ],
  RefundTemplate: [
    [
      "ID",
      "USERNAME",
      "SỐ TIỀN",
      "TRẠNG THÁI",
      "NGÀY TẠO",
      "NGƯỜI TẠO",
      "NGÀY DUYỆT",
      "NGƯỜI DUYỆT",
    ],
  ],
  PayOrderHistoryReportTemplate: [
    [
      "MÃ ĐƠN HÀNG",
      "USERNAME",
      "LOẠI THANH TOÁN",
      "SỐ TIỀN",
      "NGÀY TẠO",
      "NGƯỜI TẠO",
    ],
  ],
  PayHelpTemplate: [
    [
      "ID",
      "USERNAME",
      "TỔNG TIỀN (TỆ)",
      "TỔNG TIỀN (VNĐ)",
      "TỶ GIÁ",
      "NGÀY TẠO",
      "TRẠNG THÁI",
    ],
  ],
  PayHelpReportTemplate: [
    [
      "USERNAME",
      "TỔNG TIỀN (TỆ)",
      "TIỀN GỐC (VNĐ)",
      "TIỀN THU (VNĐ)",
      "TIỀN LỜI (VNĐ)",
      "NGÀY ĐẶT",
    ],
  ],
  OutStockSessionTemplate: [
    [
      "ID",
      "MÃ KHÁCH HÀNG",
      "USERNAME",
      "TỔNG TIỀN",
      "NGÀY TẠO",
      "TRẠNG THÁI",
      "GHI CHÚ",
      "HÌNH THỨC",
      "THANH TOÁN",
    ],
  ],
  OrderTemplate: [
    [
      "ID",
      "USERNAME",
      "MÃ ĐƠN HÀNG",
      "TÊN SẢN PHẨM",
      "THUỘC TÍNH",
      "GIÁ TỆ",
      "GIÁ VNĐ",
      "TỈ GIÁ",
      "SỐ LƯỢNG",
      "TỔNG TIỀN TỆ",
      "TỔNG TIỀN VNĐ",
      "GHI CHÚ",
      "NGÀY TẠO",
    ],
  ],
  MainOrderTemplate: [
    [
      "OrderID",
      "Username",
      "Tổng tiền",
      "Tiền đã trả",
      "Tiền còn lại",
      "Tiền hàng trên Web",
      "Phí dịch vụ",
      "Phí ship TQ",
      "Phí kiểm hàng",
      "Phí đóng gỗ",
      "Phí bảo hiểm",
      "Phụ phí",
      "Phí vận chuyển",
      "Cân nặng",
      "Trạng thái",
      "NV kinh doanh",
      "NV đặt hàng",
      "Ngày tạo",
      "Ngày đặt cọc",
      "Ngày mua hàng",
      "Ngày về kho TQ",
      "Ngày về kho VN",
      "Ngày hoàn thành",
    ],
  ],
  MainOrderRevenueReportTemplate: [
    [
      "USERNAME",
      "GIÁ TRỊ ĐƠN HÀNG",
      "TIỀN HÀNG	PHÍ ĐƠN HÀNG",
      "PHÍ MUA HÀNG",
      "VẬN CHUYỂN TQ - VN",
      "VẬN CHUYỂN NỘI ĐỊA",
      "MẶC CẢ",
      "CÂN NẶNG",
      "SỐ ĐƠN HÀNG",
      "SỐ KHÁCH HÀNG",
    ],
  ],
  MainOrderReportTemplate: [
    [
      "MÃ ĐƠN HÀNG",
      "USERNAME",
      "TÊN SHOP",
      "NV KINH DOANH",
      "PHÍ SHIP TQ",
      "PHÍ MUA HÀNG",
      "PHÍ GIAO TẬN NHÀ",
      "PHÍ KIỂM KÊ",
      "PHÍ ĐÓNG GÓI",
      "TỔNG TIỀN",
      "ĐẶT CỌC",
      "CÒN LẠI",
      "TRẠNG THÁI",
      "NGÀY TẠO",
    ],
  ],
  MainOrderForCusTemplate: [
    [
      "ORDERID",
      "TỔNG TIỀN	TIỀN CỌC",
      "USERNAME",
      "NV ĐẶT HÀNG",
      "NV KINH DOANH",
      "NGÀY ĐẶT",
      "MÃ VẬN ĐƠN",
      "TRẠNG THÁI",
    ],
  ],
  ImportCodeTemplate: [["MÃ VẬN ĐƠN", "CÂN NẶNG"]],
  HistoryPayWalletTemplate: [
    ["NGÀY", "NỘI DUNG", "SỐ TIỀN", "LOẠI GIAO DỊCH", "SỐ DƯ"],
  ],
  HistoryPayWalletReportTemplate: [
    ["NGÀY GIỜ", "NỘI DUNG", "SỐ TIỀN", "LOẠI GIAO DỊCH", "SỐ DƯ"],
  ],
  HistoryPayWalletCNYTemplate: [
    ["NGÀY", "NỘI DUNG", "SỐ TIỀN", "LOẠI GIAO DỊCH", "SỐ DƯ"],
  ],
  CustomerTemplate: [
    [
      "ID",
      "USERNAME",
      "HỌ VÀ TÊN",
      "SỐ ĐIỆN THOẠI",
      "SỐ DƯ VNĐ",
      "ĐỊA CHỈ",
      "EMAIL",
      "VIP",
      "SALER",
      "ĐẶT HÀNG",
      "TRẠNG THÁI",
      "NGÀY TẠO",
    ],
  ],
  ComplainTemplate: [
    [
      "ID",
      "USERNAME",
      "MÃ ĐƠN HÀNG",
      "SỐ TIỀN",
      "NỘI DUNG",
      "TRẠNG THÁI",
      "NGÀY TẠO",
      "NGƯỜI DUYỆT",
      "NGÀY DUYỆT",
    ],
  ],
  CatalogueTemplate: [["MÃ", "TÊN", "MÔ TẢ"]],
  BigPackageTemplate: [
    ["MÃ VẬN ĐƠN", "LOẠI HÀNG", "PHÍ SHIP", "CÂN NẶNG", "TRẠNG THÁI"],
  ],
  AdminSendUserWalletTemplate: [
    [
      "ID",
      "USERNAME",
      "SỐ TIỀN",
      "NGÂN HÀNG",
      "TRẠNG THÁI",
      "NGÀY TẠO",
      "NGƯỜI DUYỆT",
      "NGÀY DUYỆT",
    ],
  ],
  AdminSendUserWalletReportTemplate: [
    [
      "ID",
      "USERNAME",
      "SỐ TIỀN",
      "NGÂN HÀNG",
      "TRẠNG THÁI",
      "NGÀY TẠO",
      "NGƯỜI TẠO",
    ],
  ],
};
